# Generated by Django 4.1.3 on 2022-11-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Words', '0002_words_slug_alter_words_correct_alter_words_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='slug',
            field=models.SlugField(),
        ),
    ]
